// src/components/ui/Accordion.svelte
<script>
  import { ChevronDown } from 'lucide-svelte'
  import { slide } from 'svelte/transition'

  export let title = ''
  let isOpen = false

  function toggle() {
    isOpen = !isOpen
  }
</script>

<div class="border-b border-gray-100 last:border-b-0">
  <button
    on:click={toggle}
    type="button"
    class="w-full flex items-center justify-between py-4 text-left font-semibold text-gray-900 hover:text-sky-600 transition-colors"
  >
    <span class="text-lg">{title}</span>
    <ChevronDown
      class="w-5 h-5 text-gray-400 transition-transform duration-300"
      style="transform: rotate({isOpen ? '180deg' : '0deg'})"
    />
  </button>

  {#if isOpen}
    <div transition:slide={{ duration: 200 }} class="pb-4 text-gray-500 leading-relaxed">
      <slot />
    </div>
  {/if}
</div>

// src/components/ui/Accordion.tsx
'use client'

import { useState, ReactNode } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { ChevronDown } from 'lucide-react'

interface AccordionItemProps {
  title: string
  children: ReactNode
  defaultOpen?: boolean
}

export function AccordionItem({ title, children, defaultOpen = false }: AccordionItemProps) {
  const [isOpen, setIsOpen] = useState(defaultOpen)

  return (
    <div className="border-b border-gray-200 last:border-b-0">
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="w-full flex items-center justify-between py-4 text-left font-medium text-gray-900 hover:text-sky-600 transition-colors"
      >
        <span className="text-lg">{title}</span>
        <motion.span
          animate={{ rotate: isOpen ? 180 : 0 }}
          transition={{ duration: 0.2 }}
        >
          <ChevronDown className="w-5 h-5 text-gray-500" />
        </motion.span>
      </button>
      <AnimatePresence>
        {isOpen && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: 'auto', opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.2 }}
            className="overflow-hidden"
          >
            <div className="pb-4 text-gray-600 leading-relaxed">
              {children}
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  )
}

interface AccordionProps {
  children: ReactNode
  className?: string
}

export function Accordion({ children, className = '' }: AccordionProps) {
  return (
    <div className={`bg-white/70 backdrop-blur-md rounded-2xl p-6 border border-white/20 shadow-sm ${className}`}>
      {children}
    </div>
  )
}

export default Accordion
